# Generated by Django 5.2.6 on 2025-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
