# Generated by Django 5.2.6 on 2025-11-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='anyjaNeve',
            field=models.CharField(default='Ismeretlen', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='beiratkozasIdeje',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='student',
            name='hazszam',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='iranyitoszam',
            field=models.CharField(default='0000', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='kollegista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='kollegiumNeve',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='kozterJelleg',
            field=models.CharField(default='utca', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='kozterNev',
            field=models.CharField(default='Ismeretlen', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='nev',
            field=models.CharField(default='Ismeretlen', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='osztaly',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='szak',
            field=models.CharField(default='Ismeretlen', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='szuletesiHely',
            field=models.CharField(default='Ismeretlen', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='szuletesiIdo',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='student',
            name='telepules',
            field=models.CharField(default='Ismeretlen', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
