# Generated by Django 5.2.6 on 2025-11-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_anyjaneve_student_beiratkozasideje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
